services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/home/node/files
    networks:
      - n8n-internal

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    depends_on:
      - n8n
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - n8n-internal

  ytdlp-service:
    build:
      context: .
      dockerfile: ./ytdlp-service/Dockerfile
    restart: always
    container_name: ytdlp-service
    volumes:
      - ./local-files:/files
    networks:
      - n8n-internal

volumes:
  n8n_data:

networks:
  n8n-internal:
